//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bootstrap_Mvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_User
    {
        public string 表名 { get; set; }
        public Nullable<short> 字段序号 { get; set; }
        public string 字段名 { get; set; }
        public string 标识 { get; set; }
        public string 主键 { get; set; }
        public string 类型 { get; set; }
        public short 占用字节数 { get; set; }
        public Nullable<int> 长度 { get; set; }
        public int 小数位数 { get; set; }
        public string 允许空 { get; set; }
        public string 默认值 { get; set; }
    }
}
